# Generated by Django 2.2.3 on 2019-07-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0010_auto_20190708_2239'),
        ('publish', '0003_auto_20190707_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rms.Course', verbose_name='课程名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(max_length=100, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='举报人'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(max_length=100, verbose_name='创建者'),
        ),
    ]
