# Generated by Django 2.2.3 on 2019-07-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.CharField(default='匿名', max_length=100, null=True, verbose_name='举报人'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.CharField(default='匿名', max_length=100, null=True, verbose_name='创建者'),
        ),
    ]
