# Generated by Django 2.2.3 on 2019-07-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_auto_20190708_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resource',
            field=models.CharField(default=1, max_length=200, verbose_name='资源名称'),
            preserve_default=False,
        ),
    ]
