# Generated by Django 2.2.3 on 2019-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0008_auto_20190710_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='下载次数'),
        ),
    ]
