# Generated by Django 2.2.3 on 2019-07-11 17:13

from django.db import migrations, models
import publish.models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(default=1, upload_to=publish.models.image_directory_path, verbose_name='资源图标'),
            preserve_default=False,
        ),
    ]
