# Generated by Django 2.2.3 on 2019-07-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0012_resource_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_time']},
        ),
    ]
