# Generated by Django 2.2.3 on 2019-07-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0018_auto_20190718_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.Course', verbose_name='课程名称'),
        ),
    ]
