# Generated by Django 2.2.3 on 2019-07-06 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='section_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rms.SectionInfo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
