# Generated by Django 2.2.3 on 2019-07-06 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0005_auto_20190707_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_time',
            field=models.DateField(blank=True, null=True, verbose_name='成立时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.PositiveIntegerField(verbose_name='学分'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rms.Institute', verbose_name='开办学院'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='任教老师'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_hours',
            field=models.PositiveIntegerField(verbose_name='总学时'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='found_time',
            field=models.DateField(blank=True, null=True, verbose_name='成立时间'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='所在地址'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=200, verbose_name='学院名称'),
        ),
        migrations.AlterField(
            model_name='major',
            name='found_time',
            field=models.DateField(blank=True, null=True, verbose_name='成立日期'),
        ),
        migrations.AlterField(
            model_name='major',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.Institute', verbose_name='所在学院'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=200, verbose_name='专业名称'),
        ),
        migrations.AlterField(
            model_name='score',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rms.Course', verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='score',
            name='credit',
            field=models.PositiveIntegerField(default=0, verbose_name='获得学分绩点'),
        ),
        migrations.AlterField(
            model_name='score',
            name='final_grade',
            field=models.PositiveIntegerField(default=0, verbose_name='期末成绩'),
        ),
        migrations.AlterField(
            model_name='score',
            name='regular_grade1',
            field=models.PositiveIntegerField(default=0, verbose_name='平时成绩1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='regular_grade2',
            field=models.PositiveIntegerField(default=0, verbose_name='平时成绩2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_grade',
            field=models.PositiveIntegerField(default=0, verbose_name='总成绩'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rms.Institute', verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rms.Major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rms.Semester', verbose_name='学期'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='student_num',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='学生人数'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rms.Year', verbose_name='入学年份'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=100, verbose_name='学期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='section_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rms.SectionInfo', verbose_name='部门信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=8, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sno',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='学工号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('unknown', '未知')], default='unknown', max_length=8, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(max_length=100, verbose_name='年份'),
        ),
    ]
