# Generated by Django 2.2.3 on 2019-07-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0006_auto_20190707_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioninfo',
            name='semester',
            field=models.CharField(choices=[('autumn', '秋季学期'), ('spring', '春季学期'), ('summer', '夏季学期')], default='autumn', max_length=100, verbose_name='学期'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='year',
            field=models.CharField(default='%Y', max_length=100, verbose_name='入学年份'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
