# Generated by Django 2.2.3 on 2019-07-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0008_auto_20190708_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioninfo',
            name='year',
            field=models.CharField(default=2019, max_length=100, verbose_name='入学年份'),
        ),
    ]
