# Generated by Django 2.2.3 on 2019-07-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0009_auto_20190708_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('unknown', '未知')], default='student', max_length=8, verbose_name='类型'),
        ),
    ]
