# Generated by Django 2.2.3 on 2019-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0010_auto_20190708_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='teacher_num',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='教师人数'),
        ),
    ]
