# Generated by Django 2.2.3 on 2019-07-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0011_institute_teacher_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='male', max_length=8, verbose_name='性别'),
        ),
    ]
