# Generated by Django 2.2.3 on 2019-07-14 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0014_studentgrouporder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrouporder',
            name='item',
        ),
        migrations.AddField(
            model_name='studentgrouporder',
            name='student',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
