# Generated by Django 2.2.3 on 2019-07-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0016_delete_studentgrouporder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectioninfo',
            options={'ordering': ['-year', 'semester', 'institute', 'major']},
        ),
    ]
