# Generated by Django 2.2.3 on 2019-07-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0018_auto_20190715_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='final_grade',
            field=models.FloatField(default=0.0, verbose_name='期末成绩'),
        ),
        migrations.AlterField(
            model_name='score',
            name='regular_grade1',
            field=models.FloatField(default=0.0, verbose_name='平时成绩1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='regular_grade2',
            field=models.FloatField(default=0.0, verbose_name='平时成绩2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_grade',
            field=models.FloatField(default=0.0, verbose_name='总成绩'),
        ),
    ]
